apiVersion: v1
kind: ConfigMap
metadata:
  name: young-certi-api-config
  namespace: young-certi
data:
  AWS_REGION: ap-northeast-2
  S3_BUCKET: young-certi-study
  S3_QUESTIONS_KEY: sap-c02/questions.json
  
  # CloudFront 도메인, 로컬 개발 주소 작성
  CORS_ALLOWED_ORIGINS: http://localhost:15173,https://d1ndorup391ph6.cloudfront.net,https://certi.adansonia.cloud
