apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- serviceaccount.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: young-certi-backend
  newName: 474668399282.dkr.ecr.ap-northeast-2.amazonaws.com/young-certi-backend
  newTag: d65ed18fcc9a61a34e4040a0e499d66ab065eae1
